export const FAKE_DATA_CURRENT_WEATHER = {
	"location": {
			"name": "Newark",
			"region": "New Jersey",
			"country": "USA",
			"lat": 40.71,
			"lon": -74.21,
			"tz_id": "America/New_York",
			"localtime_epoch": 1629966894,
			"localtime": "2021-08-26 4:34"
	},
	"current": {
			"last_updated_epoch": 1629966600,
			"last_updated": "2021-08-26 04:30",
			"temp_c": 25.6,
			"temp_f": 78.1,
			"is_day": 0,
			"condition": {
					"text": "Partly cloudy",
					"icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
					"code": 1003
			},
			"wind_mph": 5.6,
			"wind_kph": 9,
			"wind_degree": 220,
			"wind_dir": "SW",
			"pressure_mb": 1019,
			"pressure_in": 30.09,
			"precip_mm": 0,
			"precip_in": 0,
			"humidity": 71,
			"cloud": 25,
			"feelslike_c": 27.1,
			"feelslike_f": 80.8,
			"vis_km": 16,
			"vis_miles": 9,
			"uv": 1,
			"gust_mph": 6.9,
			"gust_kph": 11.2
	},
	"forecast": {
			"forecastday": [
					{
							"date": "2021-08-26",
							"date_epoch": 1629936000,
							"day": {
									"maxtemp_c": 34.7,
									"maxtemp_f": 94.5,
									"mintemp_c": 24.5,
									"mintemp_f": 76.1,
									"avgtemp_c": 29.4,
									"avgtemp_f": 84.9,
									"maxwind_mph": 8.5,
									"maxwind_kph": 13.7,
									"totalprecip_mm": 0.3,
									"totalprecip_in": 0.01,
									"avgvis_km": 10,
									"avgvis_miles": 6,
									"avghumidity": 59,
									"daily_will_it_rain": 1,
									"daily_chance_of_rain": 73,
									"daily_will_it_snow": 0,
									"daily_chance_of_snow": 0,
									"condition": {
											"text": "Patchy rain possible",
											"icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
											"code": 1063
									},
									"uv": 8
							},
							"astro": {
									"sunrise": "06:18 AM",
									"sunset": "07:38 PM",
									"moonrise": "09:58 PM",
									"moonset": "10:25 AM",
									"moon_phase": "Last Quarter",
									"moon_illumination": "69"
							},
							"hour": [
									{
											"time_epoch": 1629950400,
											"time": "2021-08-26 00:00",
											"temp_c": 26.8,
											"temp_f": 80.2,
											"is_day": 0,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
													"code": 1003
											},
											"wind_mph": 4.9,
											"wind_kph": 7.9,
											"wind_degree": 230,
											"wind_dir": "SW",
											"pressure_mb": 1019,
											"pressure_in": 30.09,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 65,
											"cloud": 11,
											"feelslike_c": 28.5,
											"feelslike_f": 83.3,
											"windchill_c": 26.8,
											"windchill_f": 80.2,
											"heatindex_c": 28.5,
											"heatindex_f": 83.3,
											"dewpoint_c": 19.6,
											"dewpoint_f": 67.3,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 8.1,
											"gust_kph": 13,
											"uv": 1
									},
									{
											"time_epoch": 1629954000,
											"time": "2021-08-26 01:00",
											"temp_c": 26.4,
											"temp_f": 79.5,
											"is_day": 0,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
													"code": 1003
											},
											"wind_mph": 4.3,
											"wind_kph": 6.8,
											"wind_degree": 234,
											"wind_dir": "SW",
											"pressure_mb": 1019,
											"pressure_in": 30.09,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 67,
											"cloud": 10,
											"feelslike_c": 28.1,
											"feelslike_f": 82.6,
											"windchill_c": 26.4,
											"windchill_f": 79.5,
											"heatindex_c": 28.1,
											"heatindex_f": 82.6,
											"dewpoint_c": 19.7,
											"dewpoint_f": 67.5,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 6.9,
											"gust_kph": 11.2,
											"uv": 1
									},
									{
											"time_epoch": 1629957600,
											"time": "2021-08-26 02:00",
											"temp_c": 25.9,
											"temp_f": 78.6,
											"is_day": 0,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
													"code": 1003
											},
											"wind_mph": 4,
											"wind_kph": 6.5,
											"wind_degree": 237,
											"wind_dir": "WSW",
											"pressure_mb": 1019,
											"pressure_in": 30.09,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 69,
											"cloud": 11,
											"feelslike_c": 27.6,
											"feelslike_f": 81.7,
											"windchill_c": 25.9,
											"windchill_f": 78.6,
											"heatindex_c": 27.6,
											"heatindex_f": 81.7,
											"dewpoint_c": 19.7,
											"dewpoint_f": 67.5,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 6.7,
											"gust_kph": 10.8,
											"uv": 1
									},
									{
											"time_epoch": 1629961200,
											"time": "2021-08-26 03:00",
											"temp_c": 25.5,
											"temp_f": 77.9,
											"is_day": 0,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
													"code": 1003
											},
											"wind_mph": 4,
											"wind_kph": 6.5,
											"wind_degree": 241,
											"wind_dir": "WSW",
											"pressure_mb": 1019,
											"pressure_in": 30.09,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 70,
											"cloud": 10,
											"feelslike_c": 27.2,
											"feelslike_f": 81,
											"windchill_c": 25.5,
											"windchill_f": 77.9,
											"heatindex_c": 27.2,
											"heatindex_f": 81,
											"dewpoint_c": 19.6,
											"dewpoint_f": 67.3,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 6.7,
											"gust_kph": 10.8,
											"uv": 1
									},
									{
											"time_epoch": 1629964800,
											"time": "2021-08-26 04:00",
											"temp_c": 25.2,
											"temp_f": 77.4,
											"is_day": 0,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
													"code": 1003
											},
											"wind_mph": 4,
											"wind_kph": 6.5,
											"wind_degree": 238,
											"wind_dir": "WSW",
											"pressure_mb": 1019,
											"pressure_in": 30.09,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 71,
											"cloud": 5,
											"feelslike_c": 26.9,
											"feelslike_f": 80.4,
											"windchill_c": 25.2,
											"windchill_f": 77.4,
											"heatindex_c": 26.9,
											"heatindex_f": 80.4,
											"dewpoint_c": 19.6,
											"dewpoint_f": 67.3,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 6.9,
											"gust_kph": 11.2,
											"uv": 1
									},
									{
											"time_epoch": 1629968400,
											"time": "2021-08-26 05:00",
											"temp_c": 24.8,
											"temp_f": 76.6,
											"is_day": 0,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
													"code": 1003
											},
											"wind_mph": 4.5,
											"wind_kph": 7.2,
											"wind_degree": 246,
											"wind_dir": "WSW",
											"pressure_mb": 1019,
											"pressure_in": 30.09,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 73,
											"cloud": 4,
											"feelslike_c": 26.5,
											"feelslike_f": 79.7,
											"windchill_c": 24.8,
											"windchill_f": 76.6,
											"heatindex_c": 26.5,
											"heatindex_f": 79.7,
											"dewpoint_c": 19.6,
											"dewpoint_f": 67.3,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 7.8,
											"gust_kph": 12.6,
											"uv": 1
									},
									{
											"time_epoch": 1629972000,
											"time": "2021-08-26 06:00",
											"temp_c": 24.5,
											"temp_f": 76.1,
											"is_day": 0,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
													"code": 1003
											},
											"wind_mph": 3.4,
											"wind_kph": 5.4,
											"wind_degree": 265,
											"wind_dir": "W",
											"pressure_mb": 1019,
											"pressure_in": 30.09,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 75,
											"cloud": 2,
											"feelslike_c": 26.3,
											"feelslike_f": 79.3,
											"windchill_c": 24.5,
											"windchill_f": 76.1,
											"heatindex_c": 26.3,
											"heatindex_f": 79.3,
											"dewpoint_c": 19.7,
											"dewpoint_f": 67.5,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 6,
											"gust_kph": 9.7,
											"uv": 1
									},
									{
											"time_epoch": 1629975600,
											"time": "2021-08-26 07:00",
											"temp_c": 24.7,
											"temp_f": 76.5,
											"is_day": 1,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
													"code": 1003
											},
											"wind_mph": 3.1,
											"wind_kph": 5,
											"wind_degree": 268,
											"wind_dir": "W",
											"pressure_mb": 1019,
											"pressure_in": 30.1,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 75,
											"cloud": 3,
											"feelslike_c": 26.5,
											"feelslike_f": 79.7,
											"windchill_c": 24.7,
											"windchill_f": 76.5,
											"heatindex_c": 26.5,
											"heatindex_f": 79.7,
											"dewpoint_c": 20,
											"dewpoint_f": 68,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 5.1,
											"gust_kph": 8.3,
											"uv": 6
									},
									{
											"time_epoch": 1629979200,
											"time": "2021-08-26 08:00",
											"temp_c": 26.3,
											"temp_f": 79.3,
											"is_day": 1,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
													"code": 1003
											},
											"wind_mph": 2.7,
											"wind_kph": 4.3,
											"wind_degree": 279,
											"wind_dir": "W",
											"pressure_mb": 1020,
											"pressure_in": 30.11,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 70,
											"cloud": 6,
											"feelslike_c": 28.2,
											"feelslike_f": 82.8,
											"windchill_c": 26.3,
											"windchill_f": 79.3,
											"heatindex_c": 28.2,
											"heatindex_f": 82.8,
											"dewpoint_c": 20.4,
											"dewpoint_f": 68.7,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 3.6,
											"gust_kph": 5.8,
											"uv": 7
									},
									{
											"time_epoch": 1629982800,
											"time": "2021-08-26 09:00",
											"temp_c": 28,
											"temp_f": 82.4,
											"is_day": 1,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
													"code": 1003
											},
											"wind_mph": 2.7,
											"wind_kph": 4.3,
											"wind_degree": 255,
											"wind_dir": "WSW",
											"pressure_mb": 1020,
											"pressure_in": 30.12,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 63,
											"cloud": 7,
											"feelslike_c": 30.1,
											"feelslike_f": 86.2,
											"windchill_c": 28,
											"windchill_f": 82.4,
											"heatindex_c": 30.1,
											"heatindex_f": 86.2,
											"dewpoint_c": 20.3,
											"dewpoint_f": 68.5,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 3.1,
											"gust_kph": 5,
											"uv": 7
									},
									{
											"time_epoch": 1629986400,
											"time": "2021-08-26 10:00",
											"temp_c": 29.7,
											"temp_f": 85.5,
											"is_day": 1,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
													"code": 1003
											},
											"wind_mph": 4.5,
											"wind_kph": 7.2,
											"wind_degree": 231,
											"wind_dir": "SW",
											"pressure_mb": 1020,
											"pressure_in": 30.12,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 57,
											"cloud": 10,
											"feelslike_c": 32,
											"feelslike_f": 89.6,
											"windchill_c": 29.7,
											"windchill_f": 85.5,
											"heatindex_c": 32,
											"heatindex_f": 89.6,
											"dewpoint_c": 20.2,
											"dewpoint_f": 68.4,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 5.1,
											"gust_kph": 8.3,
											"uv": 7
									},
									{
											"time_epoch": 1629990000,
											"time": "2021-08-26 11:00",
											"temp_c": 33.4,
											"temp_f": 92.1,
											"is_day": 1,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
													"code": 1003
											},
											"wind_mph": 5.8,
											"wind_kph": 9.4,
											"wind_degree": 229,
											"wind_dir": "SW",
											"pressure_mb": 1020,
											"pressure_in": 30.12,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 51,
											"cloud": 16,
											"feelslike_c": 38,
											"feelslike_f": 100.4,
											"windchill_c": 33.4,
											"windchill_f": 92.1,
											"heatindex_c": 38,
											"heatindex_f": 100.4,
											"dewpoint_c": 21.9,
											"dewpoint_f": 71.4,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 6.7,
											"gust_kph": 10.8,
											"uv": 8
									},
									{
											"time_epoch": 1629993600,
											"time": "2021-08-26 12:00",
											"temp_c": 33.7,
											"temp_f": 92.7,
											"is_day": 1,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
													"code": 1003
											},
											"wind_mph": 6.5,
											"wind_kph": 10.4,
											"wind_degree": 225,
											"wind_dir": "SW",
											"pressure_mb": 1020,
											"pressure_in": 30.11,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 47,
											"cloud": 26,
											"feelslike_c": 37.4,
											"feelslike_f": 99.3,
											"windchill_c": 33.7,
											"windchill_f": 92.7,
											"heatindex_c": 37.4,
											"heatindex_f": 99.3,
											"dewpoint_c": 20.8,
											"dewpoint_f": 69.4,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 7.4,
											"gust_kph": 11.9,
											"uv": 8
									},
									{
											"time_epoch": 1629997200,
											"time": "2021-08-26 13:00",
											"temp_c": 34.4,
											"temp_f": 93.9,
											"is_day": 1,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
													"code": 1003
											},
											"wind_mph": 6.7,
											"wind_kph": 10.8,
											"wind_degree": 224,
											"wind_dir": "SW",
											"pressure_mb": 1019,
											"pressure_in": 30.09,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 44,
											"cloud": 30,
											"feelslike_c": 38,
											"feelslike_f": 100.4,
											"windchill_c": 34.4,
											"windchill_f": 93.9,
											"heatindex_c": 38,
											"heatindex_f": 100.4,
											"dewpoint_c": 20.5,
											"dewpoint_f": 68.9,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 7.8,
											"gust_kph": 12.6,
											"uv": 8
									},
									{
											"time_epoch": 1630000800,
											"time": "2021-08-26 14:00",
											"temp_c": 34.7,
											"temp_f": 94.5,
											"is_day": 1,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
													"code": 1003
											},
											"wind_mph": 6.9,
											"wind_kph": 11.2,
											"wind_degree": 225,
											"wind_dir": "SW",
											"pressure_mb": 1019,
											"pressure_in": 30.08,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 43,
											"cloud": 28,
											"feelslike_c": 38.4,
											"feelslike_f": 101.1,
											"windchill_c": 34.7,
											"windchill_f": 94.5,
											"heatindex_c": 38.4,
											"heatindex_f": 101.1,
											"dewpoint_c": 20.4,
											"dewpoint_f": 68.7,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 8.1,
											"gust_kph": 13,
											"uv": 8
									},
									{
											"time_epoch": 1630004400,
											"time": "2021-08-26 15:00",
											"temp_c": 34.5,
											"temp_f": 94.1,
											"is_day": 1,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
													"code": 1003
											},
											"wind_mph": 7.4,
											"wind_kph": 11.9,
											"wind_degree": 222,
											"wind_dir": "SW",
											"pressure_mb": 1018,
											"pressure_in": 30.06,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 43,
											"cloud": 46,
											"feelslike_c": 37.9,
											"feelslike_f": 100.2,
											"windchill_c": 34.5,
											"windchill_f": 94.1,
											"heatindex_c": 37.9,
											"heatindex_f": 100.2,
											"dewpoint_c": 20.1,
											"dewpoint_f": 68.2,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 8.5,
											"gust_kph": 13.7,
											"uv": 8
									},
									{
											"time_epoch": 1630008000,
											"time": "2021-08-26 16:00",
											"temp_c": 34.2,
											"temp_f": 93.6,
											"is_day": 1,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
													"code": 1003
											},
											"wind_mph": 7.6,
											"wind_kph": 12.2,
											"wind_degree": 217,
											"wind_dir": "SW",
											"pressure_mb": 1018,
											"pressure_in": 30.05,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 44,
											"cloud": 37,
											"feelslike_c": 37.5,
											"feelslike_f": 99.5,
											"windchill_c": 34.2,
											"windchill_f": 93.6,
											"heatindex_c": 37.5,
											"heatindex_f": 99.5,
											"dewpoint_c": 20,
											"dewpoint_f": 68,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 8.7,
											"gust_kph": 14,
											"uv": 8
									},
									{
											"time_epoch": 1630011600,
											"time": "2021-08-26 17:00",
											"temp_c": 33.4,
											"temp_f": 92.1,
											"is_day": 1,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
													"code": 1003
											},
											"wind_mph": 6.7,
											"wind_kph": 10.8,
											"wind_degree": 218,
											"wind_dir": "SW",
											"pressure_mb": 1017,
											"pressure_in": 30.04,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 45,
											"cloud": 27,
											"feelslike_c": 36.3,
											"feelslike_f": 97.3,
											"windchill_c": 33.4,
											"windchill_f": 92.1,
											"heatindex_c": 36.3,
											"heatindex_f": 97.3,
											"dewpoint_c": 19.8,
											"dewpoint_f": 67.6,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 7.8,
											"gust_kph": 12.6,
											"uv": 8
									},
									{
											"time_epoch": 1630015200,
											"time": "2021-08-26 18:00",
											"temp_c": 33.1,
											"temp_f": 91.6,
											"is_day": 1,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
													"code": 1003
											},
											"wind_mph": 6.3,
											"wind_kph": 10.1,
											"wind_degree": 222,
											"wind_dir": "SW",
											"pressure_mb": 1017,
											"pressure_in": 30.03,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 45,
											"cloud": 16,
											"feelslike_c": 35.7,
											"feelslike_f": 96.3,
											"windchill_c": 33.1,
											"windchill_f": 91.6,
											"heatindex_c": 35.7,
											"heatindex_f": 96.3,
											"dewpoint_c": 19.4,
											"dewpoint_f": 66.9,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 7.6,
											"gust_kph": 12.2,
											"uv": 8
									},
									{
											"time_epoch": 1630018800,
											"time": "2021-08-26 19:00",
											"temp_c": 32.5,
											"temp_f": 90.5,
											"is_day": 1,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
													"code": 1003
											},
											"wind_mph": 6.7,
											"wind_kph": 10.8,
											"wind_degree": 230,
											"wind_dir": "SW",
											"pressure_mb": 1017,
											"pressure_in": 30.04,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 49,
											"cloud": 13,
											"feelslike_c": 35.6,
											"feelslike_f": 96.1,
											"windchill_c": 32.5,
											"windchill_f": 90.5,
											"heatindex_c": 35.6,
											"heatindex_f": 96.1,
											"dewpoint_c": 20.5,
											"dewpoint_f": 68.9,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 8.3,
											"gust_kph": 13.3,
											"uv": 8
									},
									{
											"time_epoch": 1630022400,
											"time": "2021-08-26 20:00",
											"temp_c": 30.3,
											"temp_f": 86.5,
											"is_day": 0,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
													"code": 1003
											},
											"wind_mph": 6.7,
											"wind_kph": 10.8,
											"wind_degree": 249,
											"wind_dir": "WSW",
											"pressure_mb": 1018,
											"pressure_in": 30.05,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 56,
											"cloud": 12,
											"feelslike_c": 32.9,
											"feelslike_f": 91.2,
											"windchill_c": 30.3,
											"windchill_f": 86.5,
											"heatindex_c": 32.9,
											"heatindex_f": 91.2,
											"dewpoint_c": 20.5,
											"dewpoint_f": 68.9,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 10.5,
											"gust_kph": 16.9,
											"uv": 1
									},
									{
											"time_epoch": 1630026000,
											"time": "2021-08-26 21:00",
											"temp_c": 29.3,
											"temp_f": 84.7,
											"is_day": 0,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
													"code": 1003
											},
											"wind_mph": 7.2,
											"wind_kph": 11.5,
											"wind_degree": 239,
											"wind_dir": "WSW",
											"pressure_mb": 1018,
											"pressure_in": 30.07,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 60,
											"cloud": 13,
											"feelslike_c": 31.9,
											"feelslike_f": 89.4,
											"windchill_c": 29.3,
											"windchill_f": 84.7,
											"heatindex_c": 31.9,
											"heatindex_f": 89.4,
											"dewpoint_c": 20.8,
											"dewpoint_f": 69.4,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 11.2,
											"gust_kph": 18,
											"uv": 1
									},
									{
											"time_epoch": 1630029600,
											"time": "2021-08-26 22:00",
											"temp_c": 27.8,
											"temp_f": 82,
											"is_day": 0,
											"condition": {
													"text": "Patchy rain possible",
													"icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
													"code": 1063
											},
											"wind_mph": 8.5,
											"wind_kph": 13.7,
											"wind_degree": 235,
											"wind_dir": "SW",
											"pressure_mb": 1019,
											"pressure_in": 30.09,
											"precip_mm": 0.1,
											"precip_in": 0,
											"humidity": 66,
											"cloud": 86,
											"feelslike_c": 30.1,
											"feelslike_f": 86.2,
											"windchill_c": 27.8,
											"windchill_f": 82,
											"heatindex_c": 30.1,
											"heatindex_f": 86.2,
											"dewpoint_c": 21,
											"dewpoint_f": 69.8,
											"will_it_rain": 0,
											"chance_of_rain": 65,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 13,
											"gust_kph": 20.9,
											"uv": 1
									},
									{
											"time_epoch": 1630033200,
											"time": "2021-08-26 23:00",
											"temp_c": 26.8,
											"temp_f": 80.2,
											"is_day": 0,
											"condition": {
													"text": "Patchy rain possible",
													"icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
													"code": 1063
											},
											"wind_mph": 7.2,
											"wind_kph": 11.5,
											"wind_degree": 247,
											"wind_dir": "WSW",
											"pressure_mb": 1019,
											"pressure_in": 30.08,
											"precip_mm": 0.2,
											"precip_in": 0.01,
											"humidity": 71,
											"cloud": 78,
											"feelslike_c": 29,
											"feelslike_f": 84.2,
											"windchill_c": 26.8,
											"windchill_f": 80.2,
											"heatindex_c": 29,
											"heatindex_f": 84.2,
											"dewpoint_c": 21.2,
											"dewpoint_f": 70.2,
											"will_it_rain": 1,
											"chance_of_rain": 73,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 9,
											"vis_miles": 5,
											"gust_mph": 11.4,
											"gust_kph": 18.4,
											"uv": 1
									}
							]
					},
					{
							"date": "2021-08-27",
							"date_epoch": 1630022400,
							"day": {
									"maxtemp_c": 36.4,
									"maxtemp_f": 97.5,
									"mintemp_c": 24.8,
									"mintemp_f": 76.6,
									"avgtemp_c": 29.5,
									"avgtemp_f": 85.2,
									"maxwind_mph": 8.1,
									"maxwind_kph": 13,
									"totalprecip_mm": 8.1,
									"totalprecip_in": 0.32,
									"avgvis_km": 9.5,
									"avgvis_miles": 5,
									"avghumidity": 64,
									"daily_will_it_rain": 1,
									"daily_chance_of_rain": 85,
									"daily_will_it_snow": 0,
									"daily_chance_of_snow": 0,
									"condition": {
											"text": "Moderate rain",
											"icon": "//cdn.weatherapi.com/weather/64x64/day/302.png",
											"code": 1189
									},
									"uv": 8
							},
							"astro": {
									"sunrise": "06:19 AM",
									"sunset": "07:37 PM",
									"moonrise": "10:22 PM",
									"moonset": "11:27 AM",
									"moon_phase": "Last Quarter",
									"moon_illumination": "62"
							},
							"hour": [
									{
											"time_epoch": 1630036800,
											"time": "2021-08-27 00:00",
											"temp_c": 26.4,
											"temp_f": 79.5,
											"is_day": 0,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
													"code": 1003
											},
											"wind_mph": 6,
											"wind_kph": 9.7,
											"wind_degree": 242,
											"wind_dir": "WSW",
											"pressure_mb": 1018,
											"pressure_in": 30.07,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 73,
											"cloud": 16,
											"feelslike_c": 28.6,
											"feelslike_f": 83.5,
											"windchill_c": 26.4,
											"windchill_f": 79.5,
											"heatindex_c": 28.6,
											"heatindex_f": 83.5,
											"dewpoint_c": 21.1,
											"dewpoint_f": 70,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 10.1,
											"gust_kph": 16.2,
											"uv": 1
									},
									{
											"time_epoch": 1630040400,
											"time": "2021-08-27 01:00",
											"temp_c": 26,
											"temp_f": 78.8,
											"is_day": 0,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
													"code": 1003
											},
											"wind_mph": 6,
											"wind_kph": 9.7,
											"wind_degree": 238,
											"wind_dir": "WSW",
											"pressure_mb": 1018,
											"pressure_in": 30.07,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 74,
											"cloud": 14,
											"feelslike_c": 28.1,
											"feelslike_f": 82.6,
											"windchill_c": 26,
											"windchill_f": 78.8,
											"heatindex_c": 28.1,
											"heatindex_f": 82.6,
											"dewpoint_c": 21,
											"dewpoint_f": 69.8,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 10.5,
											"gust_kph": 16.9,
											"uv": 1
									},
									{
											"time_epoch": 1630044000,
											"time": "2021-08-27 02:00",
											"temp_c": 25.8,
											"temp_f": 78.4,
											"is_day": 0,
											"condition": {
													"text": "Patchy rain possible",
													"icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
													"code": 1063
											},
											"wind_mph": 5.6,
											"wind_kph": 9,
											"wind_degree": 246,
											"wind_dir": "WSW",
											"pressure_mb": 1018,
											"pressure_in": 30.06,
											"precip_mm": 0.2,
											"precip_in": 0.01,
											"humidity": 75,
											"cloud": 76,
											"feelslike_c": 27.9,
											"feelslike_f": 82.2,
											"windchill_c": 25.8,
											"windchill_f": 78.4,
											"heatindex_c": 27.9,
											"heatindex_f": 82.2,
											"dewpoint_c": 21.1,
											"dewpoint_f": 70,
											"will_it_rain": 0,
											"chance_of_rain": 66,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 9,
											"vis_miles": 5,
											"gust_mph": 9.6,
											"gust_kph": 15.5,
											"uv": 1
									},
									{
											"time_epoch": 1630047600,
											"time": "2021-08-27 03:00",
											"temp_c": 25.5,
											"temp_f": 77.9,
											"is_day": 0,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
													"code": 1003
											},
											"wind_mph": 5.1,
											"wind_kph": 8.3,
											"wind_degree": 256,
											"wind_dir": "WSW",
											"pressure_mb": 1018,
											"pressure_in": 30.06,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 76,
											"cloud": 13,
											"feelslike_c": 27.5,
											"feelslike_f": 81.5,
											"windchill_c": 25.5,
											"windchill_f": 77.9,
											"heatindex_c": 27.5,
											"heatindex_f": 81.5,
											"dewpoint_c": 20.9,
											"dewpoint_f": 69.6,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 8.9,
											"gust_kph": 14.4,
											"uv": 1
									},
									{
											"time_epoch": 1630051200,
											"time": "2021-08-27 04:00",
											"temp_c": 25.3,
											"temp_f": 77.5,
											"is_day": 0,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
													"code": 1003
											},
											"wind_mph": 4.3,
											"wind_kph": 6.8,
											"wind_degree": 262,
											"wind_dir": "W",
											"pressure_mb": 1018,
											"pressure_in": 30.05,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 76,
											"cloud": 12,
											"feelslike_c": 27.2,
											"feelslike_f": 81,
											"windchill_c": 25.3,
											"windchill_f": 77.5,
											"heatindex_c": 27.2,
											"heatindex_f": 81,
											"dewpoint_c": 20.8,
											"dewpoint_f": 69.4,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 7.4,
											"gust_kph": 11.9,
											"uv": 1
									},
									{
											"time_epoch": 1630054800,
											"time": "2021-08-27 05:00",
											"temp_c": 25,
											"temp_f": 77,
											"is_day": 0,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
													"code": 1003
											},
											"wind_mph": 4,
											"wind_kph": 6.5,
											"wind_degree": 259,
											"wind_dir": "W",
											"pressure_mb": 1018,
											"pressure_in": 30.05,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 77,
											"cloud": 11,
											"feelslike_c": 26.9,
											"feelslike_f": 80.4,
											"windchill_c": 25,
											"windchill_f": 77,
											"heatindex_c": 26.9,
											"heatindex_f": 80.4,
											"dewpoint_c": 20.6,
											"dewpoint_f": 69.1,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 6.9,
											"gust_kph": 11.2,
											"uv": 1
									},
									{
											"time_epoch": 1630058400,
											"time": "2021-08-27 06:00",
											"temp_c": 24.8,
											"temp_f": 76.6,
											"is_day": 0,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
													"code": 1003
											},
											"wind_mph": 4,
											"wind_kph": 6.5,
											"wind_degree": 272,
											"wind_dir": "W",
											"pressure_mb": 1018,
											"pressure_in": 30.06,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 77,
											"cloud": 12,
											"feelslike_c": 26.7,
											"feelslike_f": 80.1,
											"windchill_c": 24.8,
											"windchill_f": 76.6,
											"heatindex_c": 26.7,
											"heatindex_f": 80.1,
											"dewpoint_c": 20.5,
											"dewpoint_f": 68.9,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 7.2,
											"gust_kph": 11.5,
											"uv": 1
									},
									{
											"time_epoch": 1630062000,
											"time": "2021-08-27 07:00",
											"temp_c": 25.1,
											"temp_f": 77.2,
											"is_day": 1,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
													"code": 1003
											},
											"wind_mph": 3.1,
											"wind_kph": 5,
											"wind_degree": 293,
											"wind_dir": "WNW",
											"pressure_mb": 1019,
											"pressure_in": 30.08,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 75,
											"cloud": 11,
											"feelslike_c": 26.9,
											"feelslike_f": 80.4,
											"windchill_c": 25.1,
											"windchill_f": 77.2,
											"heatindex_c": 26.9,
											"heatindex_f": 80.4,
											"dewpoint_c": 20.3,
											"dewpoint_f": 68.5,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 5.4,
											"gust_kph": 8.6,
											"uv": 7
									},
									{
											"time_epoch": 1630065600,
											"time": "2021-08-27 08:00",
											"temp_c": 26.7,
											"temp_f": 80.1,
											"is_day": 1,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
													"code": 1003
											},
											"wind_mph": 3.4,
											"wind_kph": 5.4,
											"wind_degree": 302,
											"wind_dir": "WNW",
											"pressure_mb": 1019,
											"pressure_in": 30.09,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 68,
											"cloud": 11,
											"feelslike_c": 28.6,
											"feelslike_f": 83.5,
											"windchill_c": 26.7,
											"windchill_f": 80.1,
											"heatindex_c": 28.6,
											"heatindex_f": 83.5,
											"dewpoint_c": 20.3,
											"dewpoint_f": 68.5,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 4.7,
											"gust_kph": 7.6,
											"uv": 7
									},
									{
											"time_epoch": 1630069200,
											"time": "2021-08-27 09:00",
											"temp_c": 28.6,
											"temp_f": 83.5,
											"is_day": 1,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
													"code": 1003
											},
											"wind_mph": 4,
											"wind_kph": 6.5,
											"wind_degree": 328,
											"wind_dir": "NNW",
											"pressure_mb": 1019,
											"pressure_in": 30.1,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 61,
											"cloud": 11,
											"feelslike_c": 30.7,
											"feelslike_f": 87.3,
											"windchill_c": 28.6,
											"windchill_f": 83.5,
											"heatindex_c": 30.7,
											"heatindex_f": 87.3,
											"dewpoint_c": 20.2,
											"dewpoint_f": 68.4,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 4.7,
											"gust_kph": 7.6,
											"uv": 7
									},
									{
											"time_epoch": 1630072800,
											"time": "2021-08-27 10:00",
											"temp_c": 30.4,
											"temp_f": 86.7,
											"is_day": 1,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
													"code": 1003
											},
											"wind_mph": 3.4,
											"wind_kph": 5.4,
											"wind_degree": 344,
											"wind_dir": "NNW",
											"pressure_mb": 1019,
											"pressure_in": 30.1,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 54,
											"cloud": 9,
											"feelslike_c": 32.8,
											"feelslike_f": 91,
											"windchill_c": 30.4,
											"windchill_f": 86.7,
											"heatindex_c": 32.8,
											"heatindex_f": 91,
											"dewpoint_c": 20.1,
											"dewpoint_f": 68.2,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 3.8,
											"gust_kph": 6.1,
											"uv": 8
									},
									{
											"time_epoch": 1630076400,
											"time": "2021-08-27 11:00",
											"temp_c": 35.2,
											"temp_f": 95.4,
											"is_day": 1,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
													"code": 1003
											},
											"wind_mph": 1.1,
											"wind_kph": 1.8,
											"wind_degree": 342,
											"wind_dir": "NNW",
											"pressure_mb": 1019,
											"pressure_in": 30.09,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 49,
											"cloud": 9,
											"feelslike_c": 41.2,
											"feelslike_f": 106.2,
											"windchill_c": 35.2,
											"windchill_f": 95.4,
											"heatindex_c": 41.2,
											"heatindex_f": 106.2,
											"dewpoint_c": 22.8,
											"dewpoint_f": 73,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 1.3,
											"gust_kph": 2.2,
											"uv": 9
									},
									{
											"time_epoch": 1630080000,
											"time": "2021-08-27 12:00",
											"temp_c": 36.4,
											"temp_f": 97.5,
											"is_day": 1,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
													"code": 1003
											},
											"wind_mph": 1.3,
											"wind_kph": 2.2,
											"wind_degree": 174,
											"wind_dir": "S",
											"pressure_mb": 1018,
											"pressure_in": 30.07,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 45,
											"cloud": 9,
											"feelslike_c": 42.4,
											"feelslike_f": 108.3,
											"windchill_c": 36.4,
											"windchill_f": 97.5,
											"heatindex_c": 42.4,
											"heatindex_f": 108.3,
											"dewpoint_c": 22.4,
											"dewpoint_f": 72.3,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 1.6,
											"gust_kph": 2.5,
											"uv": 9
									},
									{
											"time_epoch": 1630083600,
											"time": "2021-08-27 13:00",
											"temp_c": 35.4,
											"temp_f": 95.7,
											"is_day": 1,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
													"code": 1003
											},
											"wind_mph": 2.2,
											"wind_kph": 3.6,
											"wind_degree": 153,
											"wind_dir": "SSE",
											"pressure_mb": 1018,
											"pressure_in": 30.06,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 42,
											"cloud": 28,
											"feelslike_c": 39.4,
											"feelslike_f": 102.9,
											"windchill_c": 35.4,
											"windchill_f": 95.7,
											"heatindex_c": 39.4,
											"heatindex_f": 102.9,
											"dewpoint_c": 20.5,
											"dewpoint_f": 68.9,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 2.5,
											"gust_kph": 4,
											"uv": 9
									},
									{
											"time_epoch": 1630087200,
											"time": "2021-08-27 14:00",
											"temp_c": 35.6,
											"temp_f": 96.1,
											"is_day": 1,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
													"code": 1003
											},
											"wind_mph": 4.5,
											"wind_kph": 7.2,
											"wind_degree": 158,
											"wind_dir": "SSE",
											"pressure_mb": 1018,
											"pressure_in": 30.05,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 41,
											"cloud": 29,
											"feelslike_c": 39.4,
											"feelslike_f": 102.9,
											"windchill_c": 35.6,
											"windchill_f": 96.1,
											"heatindex_c": 39.4,
											"heatindex_f": 102.9,
											"dewpoint_c": 20.3,
											"dewpoint_f": 68.5,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 5.1,
											"gust_kph": 8.3,
											"uv": 9
									},
									{
											"time_epoch": 1630090800,
											"time": "2021-08-27 15:00",
											"temp_c": 35.3,
											"temp_f": 95.5,
											"is_day": 1,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
													"code": 1003
											},
											"wind_mph": 6.3,
											"wind_kph": 10.1,
											"wind_degree": 157,
											"wind_dir": "SSE",
											"pressure_mb": 1017,
											"pressure_in": 30.04,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 41,
											"cloud": 27,
											"feelslike_c": 38.9,
											"feelslike_f": 102,
											"windchill_c": 35.3,
											"windchill_f": 95.5,
											"heatindex_c": 38.9,
											"heatindex_f": 102,
											"dewpoint_c": 20.1,
											"dewpoint_f": 68.2,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 7.2,
											"gust_kph": 11.5,
											"uv": 9
									},
									{
											"time_epoch": 1630094400,
											"time": "2021-08-27 16:00",
											"temp_c": 34.1,
											"temp_f": 93.4,
											"is_day": 1,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
													"code": 1003
											},
											"wind_mph": 8.1,
											"wind_kph": 13,
											"wind_degree": 171,
											"wind_dir": "S",
											"pressure_mb": 1017,
											"pressure_in": 30.03,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 44,
											"cloud": 33,
											"feelslike_c": 37.4,
											"feelslike_f": 99.3,
											"windchill_c": 34.1,
											"windchill_f": 93.4,
											"heatindex_c": 37.4,
											"heatindex_f": 99.3,
											"dewpoint_c": 20.2,
											"dewpoint_f": 68.4,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 9.2,
											"gust_kph": 14.8,
											"uv": 8
									},
									{
											"time_epoch": 1630098000,
											"time": "2021-08-27 17:00",
											"temp_c": 32.4,
											"temp_f": 90.3,
											"is_day": 1,
											"condition": {
													"text": "Patchy rain possible",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
													"code": 1063
											},
											"wind_mph": 7.2,
											"wind_kph": 11.5,
											"wind_degree": 180,
											"wind_dir": "S",
											"pressure_mb": 1017,
											"pressure_in": 30.04,
											"precip_mm": 0.1,
											"precip_in": 0,
											"humidity": 50,
											"cloud": 89,
											"feelslike_c": 35.7,
											"feelslike_f": 96.3,
											"windchill_c": 32.4,
											"windchill_f": 90.3,
											"heatindex_c": 35.7,
											"heatindex_f": 96.3,
											"dewpoint_c": 20.7,
											"dewpoint_f": 69.3,
											"will_it_rain": 0,
											"chance_of_rain": 69,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 9.2,
											"gust_kph": 14.8,
											"uv": 7
									},
									{
											"time_epoch": 1630101600,
											"time": "2021-08-27 18:00",
											"temp_c": 32.3,
											"temp_f": 90.1,
											"is_day": 1,
											"condition": {
													"text": "Patchy light drizzle",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/263.png",
													"code": 1150
											},
											"wind_mph": 1.8,
											"wind_kph": 2.9,
											"wind_degree": 143,
											"wind_dir": "SE",
											"pressure_mb": 1018,
											"pressure_in": 30.05,
											"precip_mm": 0.5,
											"precip_in": 0.02,
											"humidity": 64,
											"cloud": 55,
											"feelslike_c": 35.3,
											"feelslike_f": 95.5,
											"windchill_c": 32.3,
											"windchill_f": 90.1,
											"heatindex_c": 35.3,
											"heatindex_f": 95.5,
											"dewpoint_c": 22.1,
											"dewpoint_f": 71.8,
											"will_it_rain": 1,
											"chance_of_rain": 80,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 5,
											"vis_miles": 3,
											"gust_mph": 2.5,
											"gust_kph": 4,
											"uv": 7
									},
									{
											"time_epoch": 1630105200,
											"time": "2021-08-27 19:00",
											"temp_c": 31.1,
											"temp_f": 88,
											"is_day": 1,
											"condition": {
													"text": "Patchy rain possible",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
													"code": 1063
											},
											"wind_mph": 6.3,
											"wind_kph": 10.1,
											"wind_degree": 7,
											"wind_dir": "N",
											"pressure_mb": 1019,
											"pressure_in": 30.08,
											"precip_mm": 0.9,
											"precip_in": 0.04,
											"humidity": 77,
											"cloud": 74,
											"feelslike_c": 33.1,
											"feelslike_f": 91.6,
											"windchill_c": 31.1,
											"windchill_f": 88,
											"heatindex_c": 33.1,
											"heatindex_f": 91.6,
											"dewpoint_c": 22.7,
											"dewpoint_f": 72.9,
											"will_it_rain": 1,
											"chance_of_rain": 85,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 9,
											"vis_miles": 5,
											"gust_mph": 8.9,
											"gust_kph": 14.4,
											"uv": 7
									},
									{
											"time_epoch": 1630108800,
											"time": "2021-08-27 20:00",
											"temp_c": 30.4,
											"temp_f": 86.7,
											"is_day": 0,
											"condition": {
													"text": "Moderate rain at times",
													"icon": "//cdn.weatherapi.com/weather/64x64/night/299.png",
													"code": 1186
											},
											"wind_mph": 1.3,
											"wind_kph": 2.2,
											"wind_degree": 32,
											"wind_dir": "NNE",
											"pressure_mb": 1019,
											"pressure_in": 30.09,
											"precip_mm": 4.7,
											"precip_in": 0.19,
											"humidity": 75,
											"cloud": 74,
											"feelslike_c": 33.4,
											"feelslike_f": 92.1,
											"windchill_c": 30.4,
											"windchill_f": 86.7,
											"heatindex_c": 33.4,
											"heatindex_f": 92.1,
											"dewpoint_c": 22.1,
											"dewpoint_f": 71.8,
											"will_it_rain": 0,
											"chance_of_rain": 61,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 8,
											"vis_miles": 4,
											"gust_mph": 2,
											"gust_kph": 3.2,
											"uv": 1
									},
									{
											"time_epoch": 1630112400,
											"time": "2021-08-27 21:00",
											"temp_c": 28.3,
											"temp_f": 82.9,
											"is_day": 0,
											"condition": {
													"text": "Patchy rain possible",
													"icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
													"code": 1063
											},
											"wind_mph": 1.1,
											"wind_kph": 1.8,
											"wind_degree": 18,
											"wind_dir": "NNE",
											"pressure_mb": 1020,
											"pressure_in": 30.11,
											"precip_mm": 0.3,
											"precip_in": 0.01,
											"humidity": 74,
											"cloud": 78,
											"feelslike_c": 31.3,
											"feelslike_f": 88.3,
											"windchill_c": 28.3,
											"windchill_f": 82.9,
											"heatindex_c": 31.3,
											"heatindex_f": 88.3,
											"dewpoint_c": 21.9,
											"dewpoint_f": 71.4,
											"will_it_rain": 0,
											"chance_of_rain": 66,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 9,
											"vis_miles": 5,
											"gust_mph": 1.8,
											"gust_kph": 2.9,
											"uv": 1
									},
									{
											"time_epoch": 1630116000,
											"time": "2021-08-27 22:00",
											"temp_c": 26.4,
											"temp_f": 79.5,
											"is_day": 0,
											"condition": {
													"text": "Patchy rain possible",
													"icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
													"code": 1063
											},
											"wind_mph": 4.3,
											"wind_kph": 6.8,
											"wind_degree": 227,
											"wind_dir": "SW",
											"pressure_mb": 1020,
											"pressure_in": 30.11,
											"precip_mm": 0.4,
											"precip_in": 0.02,
											"humidity": 79,
											"cloud": 72,
											"feelslike_c": 29.1,
											"feelslike_f": 84.4,
											"windchill_c": 26.4,
											"windchill_f": 79.5,
											"heatindex_c": 29.1,
											"heatindex_f": 84.4,
											"dewpoint_c": 22.5,
											"dewpoint_f": 72.5,
											"will_it_rain": 1,
											"chance_of_rain": 83,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 9,
											"vis_miles": 5,
											"gust_mph": 6.5,
											"gust_kph": 10.4,
											"uv": 1
									},
									{
											"time_epoch": 1630119600,
											"time": "2021-08-27 23:00",
											"temp_c": 26.4,
											"temp_f": 79.5,
											"is_day": 0,
											"condition": {
													"text": "Light rain shower",
													"icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
													"code": 1240
											},
											"wind_mph": 3.1,
											"wind_kph": 5,
											"wind_degree": 248,
											"wind_dir": "WSW",
											"pressure_mb": 1020,
											"pressure_in": 30.11,
											"precip_mm": 1,
											"precip_in": 0.04,
											"humidity": 81,
											"cloud": 83,
											"feelslike_c": 29.3,
											"feelslike_f": 84.7,
											"windchill_c": 26.4,
											"windchill_f": 79.5,
											"heatindex_c": 29.3,
											"heatindex_f": 84.7,
											"dewpoint_c": 22.8,
											"dewpoint_f": 73,
											"will_it_rain": 0,
											"chance_of_rain": 60,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 4.5,
											"gust_kph": 7.2,
											"uv": 1
									}
							]
					},
					{
							"date": "2021-08-28",
							"date_epoch": 1630108800,
							"day": {
									"maxtemp_c": 26.5,
									"maxtemp_f": 79.7,
									"mintemp_c": 23.3,
									"mintemp_f": 73.9,
									"avgtemp_c": 25.2,
									"avgtemp_f": 77.4,
									"maxwind_mph": 11,
									"maxwind_kph": 17.6,
									"totalprecip_mm": 7.4,
									"totalprecip_in": 0.29,
									"avgvis_km": 9.7,
									"avgvis_miles": 6,
									"avghumidity": 81,
									"daily_will_it_rain": 1,
									"daily_chance_of_rain": 89,
									"daily_will_it_snow": 0,
									"daily_chance_of_snow": 0,
									"condition": {
											"text": "Moderate rain",
											"icon": "//cdn.weatherapi.com/weather/64x64/day/302.png",
											"code": 1189
									},
									"uv": 2
							},
							"astro": {
									"sunrise": "06:20 AM",
									"sunset": "07:35 PM",
									"moonrise": "10:49 PM",
									"moonset": "12:27 PM",
									"moon_phase": "Last Quarter",
									"moon_illumination": "55"
							},
							"hour": [
									{
											"time_epoch": 1630123200,
											"time": "2021-08-28 00:00",
											"temp_c": 26,
											"temp_f": 78.8,
											"is_day": 0,
											"condition": {
													"text": "Patchy rain possible",
													"icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
													"code": 1063
											},
											"wind_mph": 2,
											"wind_kph": 3.2,
											"wind_degree": 332,
											"wind_dir": "NNW",
											"pressure_mb": 1019,
											"pressure_in": 30.1,
											"precip_mm": 0.3,
											"precip_in": 0.01,
											"humidity": 81,
											"cloud": 81,
											"feelslike_c": 28.6,
											"feelslike_f": 83.5,
											"windchill_c": 26,
											"windchill_f": 78.8,
											"heatindex_c": 28.6,
											"heatindex_f": 83.5,
											"dewpoint_c": 22.4,
											"dewpoint_f": 72.3,
											"will_it_rain": 1,
											"chance_of_rain": 71,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 9,
											"vis_miles": 5,
											"gust_mph": 3.1,
											"gust_kph": 5,
											"uv": 1
									},
									{
											"time_epoch": 1630126800,
											"time": "2021-08-28 01:00",
											"temp_c": 25.6,
											"temp_f": 78.1,
											"is_day": 0,
											"condition": {
													"text": "Patchy rain possible",
													"icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
													"code": 1063
											},
											"wind_mph": 2,
											"wind_kph": 3.2,
											"wind_degree": 13,
											"wind_dir": "NNE",
											"pressure_mb": 1020,
											"pressure_in": 30.11,
											"precip_mm": 0.2,
											"precip_in": 0.01,
											"humidity": 82,
											"cloud": 80,
											"feelslike_c": 28,
											"feelslike_f": 82.4,
											"windchill_c": 25.6,
											"windchill_f": 78.1,
											"heatindex_c": 28,
											"heatindex_f": 82.4,
											"dewpoint_c": 22.2,
											"dewpoint_f": 72,
											"will_it_rain": 1,
											"chance_of_rain": 73,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 9,
											"vis_miles": 5,
											"gust_mph": 3.4,
											"gust_kph": 5.4,
											"uv": 1
									},
									{
											"time_epoch": 1630130400,
											"time": "2021-08-28 02:00",
											"temp_c": 25.2,
											"temp_f": 77.4,
											"is_day": 0,
											"condition": {
													"text": "Patchy rain possible",
													"icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
													"code": 1063
											},
											"wind_mph": 1.3,
											"wind_kph": 2.2,
											"wind_degree": 248,
											"wind_dir": "WSW",
											"pressure_mb": 1020,
											"pressure_in": 30.11,
											"precip_mm": 1.3,
											"precip_in": 0.05,
											"humidity": 83,
											"cloud": 71,
											"feelslike_c": 27.5,
											"feelslike_f": 81.5,
											"windchill_c": 25.2,
											"windchill_f": 77.4,
											"heatindex_c": 27.5,
											"heatindex_f": 81.5,
											"dewpoint_c": 22.1,
											"dewpoint_f": 71.8,
											"will_it_rain": 0,
											"chance_of_rain": 69,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 9,
											"vis_miles": 5,
											"gust_mph": 2.2,
											"gust_kph": 3.6,
											"uv": 1
									},
									{
											"time_epoch": 1630134000,
											"time": "2021-08-28 03:00",
											"temp_c": 24.9,
											"temp_f": 76.8,
											"is_day": 0,
											"condition": {
													"text": "Patchy rain possible",
													"icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
													"code": 1063
											},
											"wind_mph": 0.7,
											"wind_kph": 1.1,
											"wind_degree": 3,
											"wind_dir": "N",
											"pressure_mb": 1019,
											"pressure_in": 30.1,
											"precip_mm": 0.2,
											"precip_in": 0.01,
											"humidity": 84,
											"cloud": 77,
											"feelslike_c": 27.2,
											"feelslike_f": 81,
											"windchill_c": 24.9,
											"windchill_f": 76.8,
											"heatindex_c": 27.2,
											"heatindex_f": 81,
											"dewpoint_c": 22,
											"dewpoint_f": 71.6,
											"will_it_rain": 1,
											"chance_of_rain": 85,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 9,
											"vis_miles": 5,
											"gust_mph": 1.1,
											"gust_kph": 1.8,
											"uv": 1
									},
									{
											"time_epoch": 1630137600,
											"time": "2021-08-28 04:00",
											"temp_c": 24.6,
											"temp_f": 76.3,
											"is_day": 0,
											"condition": {
													"text": "Patchy rain possible",
													"icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
													"code": 1063
											},
											"wind_mph": 2.2,
											"wind_kph": 3.6,
											"wind_degree": 64,
											"wind_dir": "ENE",
											"pressure_mb": 1020,
											"pressure_in": 30.11,
											"precip_mm": 0.2,
											"precip_in": 0.01,
											"humidity": 85,
											"cloud": 79,
											"feelslike_c": 26.8,
											"feelslike_f": 80.2,
											"windchill_c": 24.6,
											"windchill_f": 76.3,
											"heatindex_c": 26.8,
											"heatindex_f": 80.2,
											"dewpoint_c": 21.9,
											"dewpoint_f": 71.4,
											"will_it_rain": 0,
											"chance_of_rain": 62,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 9,
											"vis_miles": 5,
											"gust_mph": 3.6,
											"gust_kph": 5.8,
											"uv": 1
									},
									{
											"time_epoch": 1630141200,
											"time": "2021-08-28 05:00",
											"temp_c": 24.3,
											"temp_f": 75.7,
											"is_day": 0,
											"condition": {
													"text": "Patchy rain possible",
													"icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
													"code": 1063
											},
											"wind_mph": 3.4,
											"wind_kph": 5.4,
											"wind_degree": 54,
											"wind_dir": "NE",
											"pressure_mb": 1020,
											"pressure_in": 30.11,
											"precip_mm": 0.8,
											"precip_in": 0.03,
											"humidity": 85,
											"cloud": 86,
											"feelslike_c": 26.5,
											"feelslike_f": 79.7,
											"windchill_c": 24.3,
											"windchill_f": 75.7,
											"heatindex_c": 26.5,
											"heatindex_f": 79.7,
											"dewpoint_c": 21.7,
											"dewpoint_f": 71.1,
											"will_it_rain": 1,
											"chance_of_rain": 89,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 9,
											"vis_miles": 5,
											"gust_mph": 5.4,
											"gust_kph": 8.6,
											"uv": 1
									},
									{
											"time_epoch": 1630144800,
											"time": "2021-08-28 06:00",
											"temp_c": 23.8,
											"temp_f": 74.8,
											"is_day": 0,
											"condition": {
													"text": "Patchy rain possible",
													"icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
													"code": 1063
											},
											"wind_mph": 5.4,
											"wind_kph": 8.6,
											"wind_degree": 47,
											"wind_dir": "NE",
											"pressure_mb": 1020,
											"pressure_in": 30.12,
											"precip_mm": 0.3,
											"precip_in": 0.01,
											"humidity": 88,
											"cloud": 79,
											"feelslike_c": 26,
											"feelslike_f": 78.8,
											"windchill_c": 23.8,
											"windchill_f": 74.8,
											"heatindex_c": 26,
											"heatindex_f": 78.8,
											"dewpoint_c": 21.6,
											"dewpoint_f": 70.9,
											"will_it_rain": 1,
											"chance_of_rain": 83,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 9,
											"vis_miles": 5,
											"gust_mph": 8.5,
											"gust_kph": 13.7,
											"uv": 1
									},
									{
											"time_epoch": 1630148400,
											"time": "2021-08-28 07:00",
											"temp_c": 23.3,
											"temp_f": 73.9,
											"is_day": 1,
											"condition": {
													"text": "Light rain shower",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
													"code": 1240
											},
											"wind_mph": 7.8,
											"wind_kph": 12.6,
											"wind_degree": 45,
											"wind_dir": "NE",
											"pressure_mb": 1021,
											"pressure_in": 30.14,
											"precip_mm": 0.4,
											"precip_in": 0.02,
											"humidity": 91,
											"cloud": 51,
											"feelslike_c": 25.6,
											"feelslike_f": 78.1,
											"windchill_c": 23.3,
											"windchill_f": 73.9,
											"heatindex_c": 25.6,
											"heatindex_f": 78.1,
											"dewpoint_c": 21.7,
											"dewpoint_f": 71.1,
											"will_it_rain": 1,
											"chance_of_rain": 72,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 11.6,
											"gust_kph": 18.7,
											"uv": 5
									},
									{
											"time_epoch": 1630152000,
											"time": "2021-08-28 08:00",
											"temp_c": 24,
											"temp_f": 75.2,
											"is_day": 1,
											"condition": {
													"text": "Light rain shower",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
													"code": 1240
											},
											"wind_mph": 9.2,
											"wind_kph": 14.8,
											"wind_degree": 58,
											"wind_dir": "ENE",
											"pressure_mb": 1021,
											"pressure_in": 30.15,
											"precip_mm": 2,
											"precip_in": 0.08,
											"humidity": 89,
											"cloud": 56,
											"feelslike_c": 26.3,
											"feelslike_f": 79.3,
											"windchill_c": 24,
											"windchill_f": 75.2,
											"heatindex_c": 26.3,
											"heatindex_f": 79.3,
											"dewpoint_c": 22.1,
											"dewpoint_f": 71.8,
											"will_it_rain": 1,
											"chance_of_rain": 81,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 13.6,
											"gust_kph": 22,
											"uv": 5
									},
									{
											"time_epoch": 1630155600,
											"time": "2021-08-28 09:00",
											"temp_c": 24.7,
											"temp_f": 76.5,
											"is_day": 1,
											"condition": {
													"text": "Cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
													"code": 1006
											},
											"wind_mph": 8.7,
											"wind_kph": 14,
											"wind_degree": 69,
											"wind_dir": "ENE",
											"pressure_mb": 1021,
											"pressure_in": 30.16,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 85,
											"cloud": 88,
											"feelslike_c": 27,
											"feelslike_f": 80.6,
											"windchill_c": 24.7,
											"windchill_f": 76.5,
											"heatindex_c": 27,
											"heatindex_f": 80.6,
											"dewpoint_c": 22,
											"dewpoint_f": 71.6,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 10.7,
											"gust_kph": 17.3,
											"uv": 5
									},
									{
											"time_epoch": 1630159200,
											"time": "2021-08-28 10:00",
											"temp_c": 25.3,
											"temp_f": 77.5,
											"is_day": 1,
											"condition": {
													"text": "Cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
													"code": 1006
											},
											"wind_mph": 9.2,
											"wind_kph": 14.8,
											"wind_degree": 77,
											"wind_dir": "ENE",
											"pressure_mb": 1021,
											"pressure_in": 30.16,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 82,
											"cloud": 86,
											"feelslike_c": 27.6,
											"feelslike_f": 81.7,
											"windchill_c": 25.3,
											"windchill_f": 77.5,
											"heatindex_c": 27.6,
											"heatindex_f": 81.7,
											"dewpoint_c": 21.9,
											"dewpoint_f": 71.4,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 11.2,
											"gust_kph": 18,
											"uv": 6
									},
									{
											"time_epoch": 1630162800,
											"time": "2021-08-28 11:00",
											"temp_c": 25.9,
											"temp_f": 78.6,
											"is_day": 1,
											"condition": {
													"text": "Patchy rain possible",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
													"code": 1063
											},
											"wind_mph": 9.6,
											"wind_kph": 15.5,
											"wind_degree": 86,
											"wind_dir": "E",
											"pressure_mb": 1021,
											"pressure_in": 30.16,
											"precip_mm": 0.1,
											"precip_in": 0,
											"humidity": 79,
											"cloud": 83,
											"feelslike_c": 28.3,
											"feelslike_f": 82.9,
											"windchill_c": 25.9,
											"windchill_f": 78.6,
											"heatindex_c": 28.3,
											"heatindex_f": 82.9,
											"dewpoint_c": 21.9,
											"dewpoint_f": 71.4,
											"will_it_rain": 0,
											"chance_of_rain": 61,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 11.2,
											"gust_kph": 18,
											"uv": 6
									},
									{
											"time_epoch": 1630166400,
											"time": "2021-08-28 12:00",
											"temp_c": 26.2,
											"temp_f": 79.2,
											"is_day": 1,
											"condition": {
													"text": "Patchy rain possible",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
													"code": 1063
											},
											"wind_mph": 9.4,
											"wind_kph": 15.1,
											"wind_degree": 101,
											"wind_dir": "ESE",
											"pressure_mb": 1021,
											"pressure_in": 30.16,
											"precip_mm": 0.1,
											"precip_in": 0,
											"humidity": 77,
											"cloud": 100,
											"feelslike_c": 28.6,
											"feelslike_f": 83.5,
											"windchill_c": 26.2,
											"windchill_f": 79.2,
											"heatindex_c": 28.6,
											"heatindex_f": 83.5,
											"dewpoint_c": 21.8,
											"dewpoint_f": 71.2,
											"will_it_rain": 0,
											"chance_of_rain": 70,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 11.2,
											"gust_kph": 18,
											"uv": 6
									},
									{
											"time_epoch": 1630170000,
											"time": "2021-08-28 13:00",
											"temp_c": 26.2,
											"temp_f": 79.2,
											"is_day": 1,
											"condition": {
													"text": "Patchy rain possible",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
													"code": 1063
											},
											"wind_mph": 9.4,
											"wind_kph": 15.1,
											"wind_degree": 111,
											"wind_dir": "ESE",
											"pressure_mb": 1021,
											"pressure_in": 30.16,
											"precip_mm": 0.1,
											"precip_in": 0,
											"humidity": 76,
											"cloud": 100,
											"feelslike_c": 28.5,
											"feelslike_f": 83.3,
											"windchill_c": 26.2,
											"windchill_f": 79.2,
											"heatindex_c": 28.5,
											"heatindex_f": 83.3,
											"dewpoint_c": 21.6,
											"dewpoint_f": 70.9,
											"will_it_rain": 1,
											"chance_of_rain": 81,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 11.9,
											"gust_kph": 19.1,
											"uv": 6
									},
									{
											"time_epoch": 1630173600,
											"time": "2021-08-28 14:00",
											"temp_c": 26.1,
											"temp_f": 79,
											"is_day": 1,
											"condition": {
													"text": "Light rain shower",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
													"code": 1240
											},
											"wind_mph": 9.8,
											"wind_kph": 15.8,
											"wind_degree": 113,
											"wind_dir": "ESE",
											"pressure_mb": 1021,
											"pressure_in": 30.15,
											"precip_mm": 0.9,
											"precip_in": 0.04,
											"humidity": 76,
											"cloud": 100,
											"feelslike_c": 28.3,
											"feelslike_f": 82.9,
											"windchill_c": 26.1,
											"windchill_f": 79,
											"heatindex_c": 28.3,
											"heatindex_f": 82.9,
											"dewpoint_c": 21.4,
											"dewpoint_f": 70.5,
											"will_it_rain": 0,
											"chance_of_rain": 63,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 12.8,
											"gust_kph": 20.5,
											"uv": 6
									},
									{
											"time_epoch": 1630177200,
											"time": "2021-08-28 15:00",
											"temp_c": 26.2,
											"temp_f": 79.2,
											"is_day": 1,
											"condition": {
													"text": "Overcast",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
													"code": 1009
											},
											"wind_mph": 10.5,
											"wind_kph": 16.9,
											"wind_degree": 115,
											"wind_dir": "ESE",
											"pressure_mb": 1021,
											"pressure_in": 30.14,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 74,
											"cloud": 95,
											"feelslike_c": 28.3,
											"feelslike_f": 82.9,
											"windchill_c": 26.2,
											"windchill_f": 79.2,
											"heatindex_c": 28.3,
											"heatindex_f": 82.9,
											"dewpoint_c": 21.2,
											"dewpoint_f": 70.2,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 12.1,
											"gust_kph": 19.4,
											"uv": 6
									},
									{
											"time_epoch": 1630180800,
											"time": "2021-08-28 16:00",
											"temp_c": 26.5,
											"temp_f": 79.7,
											"is_day": 1,
											"condition": {
													"text": "Overcast",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
													"code": 1009
											},
											"wind_mph": 11,
											"wind_kph": 17.6,
											"wind_degree": 115,
											"wind_dir": "ESE",
											"pressure_mb": 1020,
											"pressure_in": 30.13,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 73,
											"cloud": 93,
											"feelslike_c": 28.7,
											"feelslike_f": 83.7,
											"windchill_c": 26.5,
											"windchill_f": 79.7,
											"heatindex_c": 28.7,
											"heatindex_f": 83.7,
											"dewpoint_c": 21.1,
											"dewpoint_f": 70,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 12.5,
											"gust_kph": 20.2,
											"uv": 6
									},
									{
											"time_epoch": 1630184400,
											"time": "2021-08-28 17:00",
											"temp_c": 26.1,
											"temp_f": 79,
											"is_day": 1,
											"condition": {
													"text": "Patchy rain possible",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
													"code": 1063
											},
											"wind_mph": 10.5,
											"wind_kph": 16.9,
											"wind_degree": 115,
											"wind_dir": "ESE",
											"pressure_mb": 1020,
											"pressure_in": 30.13,
											"precip_mm": 0.1,
											"precip_in": 0,
											"humidity": 74,
											"cloud": 88,
											"feelslike_c": 28.2,
											"feelslike_f": 82.8,
											"windchill_c": 26.1,
											"windchill_f": 79,
											"heatindex_c": 28.2,
											"heatindex_f": 82.8,
											"dewpoint_c": 21,
											"dewpoint_f": 69.8,
											"will_it_rain": 0,
											"chance_of_rain": 67,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 12.3,
											"gust_kph": 19.8,
											"uv": 6
									},
									{
											"time_epoch": 1630188000,
											"time": "2021-08-28 18:00",
											"temp_c": 25.8,
											"temp_f": 78.4,
											"is_day": 1,
											"condition": {
													"text": "Cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
													"code": 1006
											},
											"wind_mph": 9.8,
											"wind_kph": 15.8,
											"wind_degree": 108,
											"wind_dir": "ESE",
											"pressure_mb": 1020,
											"pressure_in": 30.13,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 75,
											"cloud": 74,
											"feelslike_c": 27.8,
											"feelslike_f": 82,
											"windchill_c": 25.8,
											"windchill_f": 78.4,
											"heatindex_c": 27.8,
											"heatindex_f": 82,
											"dewpoint_c": 20.9,
											"dewpoint_f": 69.6,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 12.1,
											"gust_kph": 19.4,
											"uv": 6
									},
									{
											"time_epoch": 1630191600,
											"time": "2021-08-28 19:00",
											"temp_c": 25.4,
											"temp_f": 77.7,
											"is_day": 1,
											"condition": {
													"text": "Partly cloudy",
													"icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
													"code": 1003
											},
											"wind_mph": 9.6,
											"wind_kph": 15.5,
											"wind_degree": 102,
											"wind_dir": "ESE",
											"pressure_mb": 1020,
											"pressure_in": 30.13,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 76,
											"cloud": 62,
											"feelslike_c": 27.4,
											"feelslike_f": 81.3,
											"windchill_c": 25.4,
											"windchill_f": 77.7,
											"heatindex_c": 27.4,
											"heatindex_f": 81.3,
											"dewpoint_c": 20.9,
											"dewpoint_f": 69.6,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 12.5,
											"gust_kph": 20.2,
											"uv": 7
									},
									{
											"time_epoch": 1630195200,
											"time": "2021-08-28 20:00",
											"temp_c": 25,
											"temp_f": 77,
											"is_day": 0,
											"condition": {
													"text": "Light rain shower",
													"icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
													"code": 1240
											},
											"wind_mph": 9.2,
											"wind_kph": 14.8,
											"wind_degree": 99,
											"wind_dir": "E",
											"pressure_mb": 1020,
											"pressure_in": 30.13,
											"precip_mm": 0.2,
											"precip_in": 0.01,
											"humidity": 79,
											"cloud": 69,
											"feelslike_c": 27,
											"feelslike_f": 80.6,
											"windchill_c": 25,
											"windchill_f": 77,
											"heatindex_c": 27,
											"heatindex_f": 80.6,
											"dewpoint_c": 21,
											"dewpoint_f": 69.8,
											"will_it_rain": 0,
											"chance_of_rain": 65,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 11.9,
											"gust_kph": 19.1,
											"uv": 1
									},
									{
											"time_epoch": 1630198800,
											"time": "2021-08-28 21:00",
											"temp_c": 24.7,
											"temp_f": 76.5,
											"is_day": 0,
											"condition": {
													"text": "Patchy rain possible",
													"icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
													"code": 1063
											},
											"wind_mph": 8.5,
											"wind_kph": 13.7,
											"wind_degree": 97,
											"wind_dir": "E",
											"pressure_mb": 1021,
											"pressure_in": 30.15,
											"precip_mm": 0.1,
											"precip_in": 0,
											"humidity": 81,
											"cloud": 81,
											"feelslike_c": 26.8,
											"feelslike_f": 80.2,
											"windchill_c": 24.7,
											"windchill_f": 76.5,
											"heatindex_c": 26.8,
											"heatindex_f": 80.2,
											"dewpoint_c": 21.3,
											"dewpoint_f": 70.3,
											"will_it_rain": 1,
											"chance_of_rain": 89,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 11,
											"gust_kph": 17.6,
											"uv": 1
									},
									{
											"time_epoch": 1630202400,
											"time": "2021-08-28 22:00",
											"temp_c": 24.5,
											"temp_f": 76.1,
											"is_day": 0,
											"condition": {
													"text": "Overcast",
													"icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
													"code": 1009
											},
											"wind_mph": 8.5,
											"wind_kph": 13.7,
											"wind_degree": 84,
											"wind_dir": "E",
											"pressure_mb": 1021,
											"pressure_in": 30.14,
											"precip_mm": 0,
											"precip_in": 0,
											"humidity": 82,
											"cloud": 96,
											"feelslike_c": 26.6,
											"feelslike_f": 79.9,
											"windchill_c": 24.5,
											"windchill_f": 76.1,
											"heatindex_c": 26.6,
											"heatindex_f": 79.9,
											"dewpoint_c": 21.2,
											"dewpoint_f": 70.2,
											"will_it_rain": 0,
											"chance_of_rain": 0,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 11.2,
											"gust_kph": 18,
											"uv": 1
									},
									{
											"time_epoch": 1630206000,
											"time": "2021-08-28 23:00",
											"temp_c": 24.4,
											"temp_f": 75.9,
											"is_day": 0,
											"condition": {
													"text": "Patchy rain possible",
													"icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
													"code": 1063
											},
											"wind_mph": 7.8,
											"wind_kph": 12.6,
											"wind_degree": 79,
											"wind_dir": "E",
											"pressure_mb": 1021,
											"pressure_in": 30.14,
											"precip_mm": 0.1,
											"precip_in": 0,
											"humidity": 82,
											"cloud": 100,
											"feelslike_c": 26.4,
											"feelslike_f": 79.5,
											"windchill_c": 24.4,
											"windchill_f": 75.9,
											"heatindex_c": 26.4,
											"heatindex_f": 79.5,
											"dewpoint_c": 21,
											"dewpoint_f": 69.8,
											"will_it_rain": 1,
											"chance_of_rain": 81,
											"will_it_snow": 0,
											"chance_of_snow": 0,
											"vis_km": 10,
											"vis_miles": 6,
											"gust_mph": 10.3,
											"gust_kph": 16.6,
											"uv": 1
									}
							]
					}
			]
	}
}